== Introduction

=== Why MIC Core
The exchange and reuse of simulation models within the company and with external partners is becoming increasingly important.

For efficient exchange and reuse 

* Information, metadata about the properties of the models is required (what does the model represent, which effects are implemented) 
* as well as administrative information (name, owner, version,...).

Currently there are several standards for model meta data, or they are being developed from several organisations


=== What is MIC Core [[what-is-mic-core]]
MIC Core is defining a standard of core attributes (key information on simulation models that enables proper useage in the usecases) that other standards can adopt, extend, refine.
Goal is to have a set of aligned attributes, that means

* we are focussing on meta data for simulation models
* also link to further detailed information which is needed for deeper traceability
  

=== Overview
In the moment existing "standards" for simulation model meta data adress specific use cases, engineering domains or simulation levels like causal, acausal, geometry level, realtime,.... 
We want to extract and align the core information from this approaches for

* traceability 
* support implementation in tools
* not focusing
** on process information
** or how to implement

We are open to future transfer of that specification to an other offical standardization body

* in the moment it is a cooperation of organizations
* the harmonization activity is result of a long standing cooperation of irt-systemX and prostep ivip, as well as more resent exchanges with other organisations   
     
=== Properties and Guiding Ideas
The goal of MIC Core is not to have one standard, but to identify and harmonize the overlapping attributes.
So, there is a common aligned part (MIC-Core) of attributes in every standard, but also, standard specific attributes according to the different use cases, domains in the standards.
The standards will stay independent but will have aligned parts.

Approach:

We identified similar attributes in the standards like 

* model.name
* General information.Name
* ModelName  
and definded a "Common Attribute Name" *Model Name*. 
The specific attributes differ slightly due to the naming conventions in the different standards. The important point was then the alignment of explanation and interpretation of the attribute name. With that approach a mapping and common understanding is achived. 

We introduced three different kinds of attributes: Mandatory, Recommended, Optional.

* Attributes are mandatory, if they are essential for traceability
* Attributes are recommended, if the information is in general of high importance for understanding
* Attributes are optional, if they are of importance in special use cases


=== How to Read This Document

Conventions used in this document:

* Non-normative text is given in square brackets in italic font: _[Especially examples are defined in this style.]_

* The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in https://tools.ietf.org/html/rfc2119[RFC 2119] (regardless of formatting and capitalization).

