== Introduction

=== Why MIC Core
The exchange and reuse of simulation models within the company and with external partners is becoming increasingly important.

For efficient exchange and reuse 

* Information, metadata about the properties of the models is required (what does the model represent, which effects are implemented) 
* as well as administrative information (name, owner, version,...).

Currently there are several standards for model meta data, or they are being developed from several organisations


=== What is MIC Core [[what-is-mic-core]]
MIC Core is defining a standard of core attributes (key information on simulation models that enables proper useage in the usecases) that other standards can adopt, extend, refine.
Goal is to have a set of aligned attributes, that means

* we are focussing on meta data for simulation models
* also link to further detailed information which is needed for deeper traceability
  
The development of MIC Core was prompted by the Model Identity Card (MIC) (see <<MIC>>) and other metadata standards and the realization that certain core attributes should be standardized across the different metadata standards. 

=== Overview
In the moment existing "standards" for simulation model meta data adress specific use cases, engineering domains or simulation levels like causal, acausal, geometry level, realtime,.... 
We want to extract and align the core information from this approaches for

* traceability 
* support implementation in tools
* not focusing
** on process information
** or how to implement

We are open to future transfer of that specification to an other offical standardization body

* in the moment it is a cooperation of organizations
* the harmonization activity is result of a long standing cooperation of irt-systemX and prostep ivip, as well as more resent exchanges with other organisations   
     
=== Properties and Guiding Ideas
The goal of MIC Core is not to have one standard, but to identify and harmonize the overlapping attributes.
So, there is a common aligned part (MIC Core) of attributes in every standard, but also, standard specific attributes according to the different use cases, domains in the standards.
The standards will stay independent but will have aligned parts.

Approach:

We identified similar attributes in the standards like 

* model.name
* General information.Name
* ModelName  

and definded a "Common Attribute Name" *Model Name*. 

The specific attributes differ slightly due to the naming conventions in the different standards. The important point was then the alignment of explanation and interpretation of the attribute name. With that approach a mapping and common understanding is achived. 

We introduced three different kinds of attributes: Mandatory, Recommended, Optional.

* Attributes are *mandatory*, if they are essential for traceability
* Attributes are *recommended*, if the information is in general of high importance for understanding
* Attributes are *optional*, if they are  important in special use cases

=== Versioning

This specification uses semantic version numbers, as defined in <<PW13>>, where the standard version consists of a triple of version numbers, consisting of major version, minor version, and patch version numbers.

In the context of MIC Core, major versions can add, delete or change attribute definitions, minor versions can only add or clarify attribute definitions, and patch versions can only clarify attribute definitions.

=== How to Apply this Standard

This specification is directed at authors of meta-data and meta-data format standards.
It is intended that standards that want to adopt the MIC Core set of attributes shall do so by claiming conformance as specified in section <<mic-core-conformance>>.
This involves the adoption of the attribute definitions of the MIC Core under the rules set down in section <<mic-core-conformance>>.

End users of these standards will look towards the standards for the full specifications of all attributes, whether adopted from MIC Core or not.

=== How to Read This Document

Conventions used in this document:

* Non-normative text is given in square brackets in italic font: _[Especially examples are defined in this style.]_

* The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in <<RFC2119>> (regardless of formatting and capitalization).

== Implementation of MIC-Core in the SRMD metadata format

=== Introduction

In the following, an exemplary implementation of the MIC-Core standard into the SRMD metadata format will be shown.
The SRMD (Simulation Resoure Meta Data) metadata format is a subset of the SSP traceability STMD (Simulation Task Meta Data) format. These formats are part of the Modelica Association Project SSP (System Structuring and Parametrization).
The SRMD format allows to specify any metadata, attributes in the form of key value pairs. The format description also specifies where this metadata file should be stored in an FMU or SSP (link to SSP traceability).

=== Maping of MIC-Core attributes to the SRMD format

The following table shows the implementation.
In the first column the attributes defined in the MIC core are listed.
The second column lists the conversion of the attribute names to SRMD. For easier machine processability, clustering via presented terms separated by period is used here. No spaces are used.
In column 3 an abbreviated explanation of the attributes is listed

[cols="1>m,2^e,7<",width="70%",align="center",frame="topbot",options="header"]
|===
| MIC-Core Name| SRMD Mapping | Short Explanation
| Model name | administrative-data.model.name | Human-readable way of referring to the model. Usually short and clear. Not necessarily unique
| Model identifier | administrative-data.model.identifier | Unique identifier for the model.
| Model description | administrative-data.model.description | Human-readable, textual, general overview. Highlights important information about the model.
| Model supplier | administrative-data.model.supplier | The responsible body and, if applicable, organizational unit within the body, that is responsible for supplying the model.
| Model confidentiality level | administrative-data.model.confidentiality-level | Protection level to apply to the model.
| Legal restriction | administrative-data.legal-restriction | Defines the rules governing the distribution and usage of the simulation model, including licensing, 
| Release | administrative-data.release | Unique identifier, preferably human-readable (i.e. semantically meaningfull), for the release of a particular simulation model.
| Release date | administrative-data.release.date | Date, and possibly time and timezone, of the release of a simulation model. Must respect ISO 8601.
| Release type| administrative-data.release.type | Relates to the maturity of the model.
| Model purpose | purpose-objectives.model | Purpose for which the model has been built/validated.
| Modelled entity | subject-information.modelled-entity | Name or description of the object represented by the simulation model.
| Modeling choice | implementation.modeling-choice | Explanation of the modeling choices, assumptions or simplifications made during the implementation of the model.
| Model limitations | implementation.model.limitations | Restrictions on the use of the model.
| Model classification | implementation.model.classification | Keyword-based classifications of the model in terms, for example, of physics, engineering or implementation.
| Software and hardware environment requirements | implementation.software-hardware-environment-requirements | Requirements regarding the software and hardware environment of the model.
| Verification status | verification-validation.verification-status | Indicates whether a given verification procedure has been followed to successfully reach verification criteria.
| Validation status | verification-validation.validation-status | Indicates whether a given validation procedure has been followed to successfully reach validation criteria.
| Verification & Validation procedure and criteria | verification-validation.procedure-criteria | Steps and methods followed as well as criteria to reach. Verification and validation can be covered together or separately.
| Verification & Validation report | verification-validation.report | Reports describing the results of the verification and validation.
|===

=== XML SRMD-Schema for MIC-Core

In the following the according XML SRMD schema is shown. 

=== Example  

In the following a little example is shown.
At the section “verification-validation.report” it is shown how multiple entries of an attribute are handled.
It is also shown how with the type approach of the SRMD format different name spaces or mixing of classifications from different standards, company specific classifications can be handled
