name: Build Spec

on:
  push:
    branches-ignore:
      - 'temp/*'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read
  actions: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  
  generate-html:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Generate revnumber
      run: |
        [[ $GITHUB_REF_TYPE == "tag" ]] && REVNUMBER=${GITHUB_REF:11} || REVNUMBER=${GITHUB_SHA:0:7}
        echo GITHUB_SHA:      $GITHUB_SHA
        echo GITHUB_REF_TYPE: $GITHUB_REF_TYPE
        echo GITHUB_REF:      $GITHUB_REF
        echo REVNUMBER:       $REVNUMBER
        echo "REVNUMBER=$REVNUMBER" >> $GITHUB_ENV

    - name: Create build directory
      run: |
        mkdir -p build/images

    - name: Generate HTML
      uses: avattathil/asciidoctor-action@master
      with:
        program: "asciidoctor --base-dir . --destination-dir=build --backend=html5 --attribute=revnumber=${{ env.REVNUMBER }} --attribute=revdate=$(date +%F) docs/index.adoc"

    - name: Copy resources
      run: |
        cp docs/images/* build/images

    - name: Create ZIP archive
      uses: actions/upload-artifact@v4
      with:
        name: MIC-Core-Specification
        path: build/*
        if-no-files-found: error

    - name: Extract branch name
      id: extract_branch
      shell: bash
      run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT

    - name: Move to published directory
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      shell: bash
      run: mkdir _site && mv build _site/${{ steps.extract_branch.outputs.branch }}

    - name: Upload Pages artifact
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: actions/upload-pages-artifact@v4

    - name: Deploy to Github Pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      id: deployment
      uses: actions/deploy-pages@v4
